//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietPhieuMuon
    {
        [DisplayName("Mã nhân viên")]
        
        public int MaCT { get; set; }
        [DisplayName("Mã phiếu mượn")]
        public Nullable<int> MaPM { get; set; }
        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Xin vui lòng nhập")]
        public int SoLuong { get; set; }
        [DisplayName("Mã sách")]
        [Required(ErrorMessage = "Xin vui lòng nhập")]
        public Nullable<int> MaSach { get; set; }
    
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
