//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Nguoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguoi()
        {
            this.DocGias = new HashSet<DocGia>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaNguoi { get; set; }
        [DisplayName("Họ tên")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string HoTen { get; set; }
        [DisplayName("Giới tính")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string Gioitinh { get; set; }
        [DisplayName("Ngày sinh")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public System.DateTime NgaySinh { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string DiaChi { get; set; }
        [DisplayName("Số điện thoại")]
        [Phone(ErrorMessage = "Số diện thoại không hợp lệ")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string Sdt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocGia> DocGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
