//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PhieuMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuon()
        {
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
            this.PhieuPhats = new HashSet<PhieuPhat>();
        }

        [DisplayName("Mã phiếu mượn")]
        public int MaPM { get; set; }
        [DisplayName("Mã độc giả")]

        public Nullable<int> MaDG { get; set; }
        [DisplayName("Mã nhân viên")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string MaNV { get; set; }
        [DisplayName("Ngày mượn")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public System.DateTime NgayMuon { get; set; }
        [DisplayName("Ngày trả")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public System.DateTime NgayTra { get; set; }
        [DisplayName("Lựa chọn")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public int LuaChon { get; set; }
        [DisplayName("Trạng thái ")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
        public virtual LuaChon LuaChon1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuPhat> PhieuPhats { get; set; }
        public virtual TrangThai TrangThai1 { get; set; }
        public string ErMess { get; internal set; }
    }
}
