//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [DisplayName("Tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập tài khoản")]
        [MinLength(6,ErrorMessage ="Tài khoản tối thiểu 6 kí tự")]
        public string TaiKhoan1 { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        [MinLength(6, ErrorMessage = "Mật khẩu tối thiểu 6 kí tự")]
        
        public string MatKhau { get; set; }
        [DisplayName("Loại tài khoản")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public Nullable<int> LoaiTK { get; set; }
        [DisplayName("Mã nhân viên")]
        [Required(ErrorMessage = "Vui lòng nhập thông tin")]
        public string MaNV { get; set; }
    
        public virtual LoaiTK LoaiTK1 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public string LoginErrorMessage { get; internal set; }
        public string ErMes { get; internal set; }
    }
}
